spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jdbc:
    mysql:
      datasource:
        url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
        username: user
        password: password
    h2:
      console:
        enabled: false