jdbc:
    h2:
      datasource:
        url: jdbc:h2:mem:edusurvay;INIT=CREATE SCHEMA IF NOT EXISTS EDUSURVAY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
      console:
        enabled: true
        path: /h2-console